condense_wildcard_suffixes = true
edition = "2018"
fn_args_layout = "Compressed"
# fn_single_line = true
format_code_in_doc_comments = true
max_width = 140
# merge_imports = true
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
tab_spaces = 2
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
